name: pro_binary
description: Efficient binary serialization library for Dart. Encodes and decodes various data types.

version: 2.1.0

repository: https://github.com/pro100andrey/pro_binary
issue_tracker: https://github.com/pro100andrey/pro_binary/issues
homepage: https://github.com/pro100andrey/pro_binary
documentation: https://github.com/pro100andrey/pro_binary/blob/main/README.md

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - binary
  - serialization
  - deserialization

environment:
  sdk: ^3.10.0

dev_dependencies:
  benchmark_harness: ^2.4.0
  pro_lints: ^5.1.0
  test: ^1.28.0

